packages:
  - "apps/*"
  - "packages/*"

# Define a catalog of version ranges (See https://pnpm.io/catalogs)
catalog:
  react: 18.3.1
  react-dom: 18.3.1
  "@types/react": 18.3.28
  "@types/react-dom": 18.3.7
  tailwindcss: 4.1.18
