/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MoviesLayoutImport } from './routes/movies/_layout'

// Create Virtual Routes

const MoviesImport = createFileRoute('/movies')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()
const UsersIndexLazyImport = createFileRoute('/users/')()
const MoviesLayoutIndexLazyImport = createFileRoute('/movies/_layout/')()

// Create/Update Routes

const MoviesRoute = MoviesImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRoute,
} as any)

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const UsersIndexLazyRoute = UsersIndexLazyImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/users/index.lazy').then((d) => d.Route))

const MoviesLayoutRoute = MoviesLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => MoviesRoute,
} as any)

const MoviesLayoutIndexLazyRoute = MoviesLayoutIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MoviesLayoutRoute,
} as any).lazy(() =>
  import('./routes/movies/_layout/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesImport
      parentRoute: typeof rootRoute
    }
    '/movies/_layout': {
      id: '/movies/_layout'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesLayoutImport
      parentRoute: typeof MoviesRoute
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/movies/_layout/': {
      id: '/movies/_layout/'
      path: '/'
      fullPath: '/movies/'
      preLoaderRoute: typeof MoviesLayoutIndexLazyImport
      parentRoute: typeof MoviesLayoutImport
    }
  }
}

// Create and export the route tree

interface MoviesLayoutRouteChildren {
  MoviesLayoutIndexLazyRoute: typeof MoviesLayoutIndexLazyRoute
}

const MoviesLayoutRouteChildren: MoviesLayoutRouteChildren = {
  MoviesLayoutIndexLazyRoute: MoviesLayoutIndexLazyRoute,
}

const MoviesLayoutRouteWithChildren = MoviesLayoutRoute._addFileChildren(
  MoviesLayoutRouteChildren,
)

interface MoviesRouteChildren {
  MoviesLayoutRoute: typeof MoviesLayoutRouteWithChildren
}

const MoviesRouteChildren: MoviesRouteChildren = {
  MoviesLayoutRoute: MoviesLayoutRouteWithChildren,
}

const MoviesRouteWithChildren =
  MoviesRoute._addFileChildren(MoviesRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/movies': typeof MoviesLayoutRouteWithChildren
  '/users': typeof UsersIndexLazyRoute
  '/movies/': typeof MoviesLayoutIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/movies': typeof MoviesLayoutIndexLazyRoute
  '/users': typeof UsersIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/movies': typeof MoviesRouteWithChildren
  '/movies/_layout': typeof MoviesLayoutRouteWithChildren
  '/users/': typeof UsersIndexLazyRoute
  '/movies/_layout/': typeof MoviesLayoutIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/movies' | '/users' | '/movies/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/movies' | '/users'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/movies'
    | '/movies/_layout'
    | '/users/'
    | '/movies/_layout/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutLazyRoute: typeof AboutLazyRoute
  MoviesRoute: typeof MoviesRouteWithChildren
  UsersIndexLazyRoute: typeof UsersIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutLazyRoute: AboutLazyRoute,
  MoviesRoute: MoviesRouteWithChildren,
  UsersIndexLazyRoute: UsersIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/movies",
        "/users/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/movies": {
      "filePath": "movies",
      "children": [
        "/movies/_layout"
      ]
    },
    "/movies/_layout": {
      "filePath": "movies/_layout.tsx",
      "parent": "/movies",
      "children": [
        "/movies/_layout/"
      ]
    },
    "/users/": {
      "filePath": "users/index.lazy.tsx"
    },
    "/movies/_layout/": {
      "filePath": "movies/_layout/index.lazy.tsx",
      "parent": "/movies/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
